insert into ACCOUNT (ID,CUSTOMERNAME,CUSTOMERAGE,PRIMARYACCOUNTNUMBER,CUTOMERID) values(11,'Parantap',20,'Harvest-Accnt-1','1234acb12p1')
insert into ACCOUNT (ID,CUSTOMERNAME,CUSTOMERAGE,PRIMARYACCOUNTNUMBER,CUTOMERID) values(21,'Mathur',60,'Harvest-Accnt-2','1234acb12p2')
insert into ACCOUNT (ID,CUSTOMERNAME,CUSTOMERAGE,PRIMARYACCOUNTNUMBER,CUTOMERID) values(31,'simba',22,'Harvest-Accnt-3','1234acb12p3')
insert into ACCOUNT (ID,CUSTOMERNAME,CUSTOMERAGE,PRIMARYACCOUNTNUMBER,CUTOMERID) values(41,'liyaya',23,'Harvest-Accnt-4','1234acb12p4') 